-- MySQL Script generated by MySQL Workbench
-- Mon May  2 23:50:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema BuyMe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BuyMe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BuyMe` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `BuyMe` ;

-- -----------------------------------------------------
-- Table `BuyMe`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyMe`.`accounts` (
  `username` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BuyMe`.`end_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyMe`.`end_users` (
  `end_username` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `anon` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`end_username`),
  CONSTRAINT `end_username`
    FOREIGN KEY (`end_username`)
    REFERENCES `BuyMe`.`accounts` (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BuyMe`.`bidders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyMe`.`bidders` (
  `listing_id` INT NULL DEFAULT NULL,
  `bidder_id` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `current_bid` DOUBLE NULL DEFAULT NULL,
  `upper_bid_limit` DOUBLE NULL DEFAULT NULL,
  INDEX `bidder_id_idx` (`bidder_id` ASC) VISIBLE,
  CONSTRAINT `bidder_id`
    FOREIGN KEY (`bidder_id`)
    REFERENCES `BuyMe`.`end_users` (`end_username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BuyMe`.`video_game_consoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyMe`.`video_game_consoles` (
  `console_id` INT NOT NULL,
  `manufacturer` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `model` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `color` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `new_or_used` VARCHAR(5) NULL DEFAULT NULL,
  `storage_space` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `warranty` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `resolution` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`console_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BuyMe`.`listings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyMe`.`listings` (
  `listing_id` INT NOT NULL,
  `start_price` DOUBLE NOT NULL,
  `highest_bid` DOUBLE NULL DEFAULT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `minimum_price` DOUBLE NOT NULL,
  `increment_price` DOUBLE NOT NULL,
  `seller_id` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `consoleID` INT NULL DEFAULT NULL,
  `title` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`listing_id`),
  INDEX `seller_id_idx` (`seller_id` ASC) VISIBLE,
  INDEX `consoleID_idx` (`consoleID` ASC) VISIBLE,
  CONSTRAINT `consoleID`
    FOREIGN KEY (`consoleID`)
    REFERENCES `BuyMe`.`video_game_consoles` (`console_id`),
  CONSTRAINT `seller_id`
    FOREIGN KEY (`seller_id`)
    REFERENCES `BuyMe`.`end_users` (`end_username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BuyMe`.`support_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyMe`.`support_record` (
  `support_ticket` INT NOT NULL,
  `staff_id` INT NULL DEFAULT NULL,
  `user_name` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`support_ticket`),
  INDEX `staff_id_idx` (`staff_id` ASC) VISIBLE,
  INDEX `user_name_idx` (`user_name` ASC) VISIBLE,
  CONSTRAINT `user_name`
    FOREIGN KEY (`user_name`)
    REFERENCES `BuyMe`.`accounts` (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BuyMe`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyMe`.`message` (
  `sender` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `date_time` DATETIME NULL DEFAULT NULL,
  `ticket` INT NULL DEFAULT NULL,
  `message` VARCHAR(300) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  INDEX `ticket_idx` (`ticket` ASC) VISIBLE,
  INDEX `user_name_idx` (`sender` ASC) VISIBLE,
  CONSTRAINT `sender`
    FOREIGN KEY (`sender`)
    REFERENCES `BuyMe`.`accounts` (`username`),
  CONSTRAINT `ticket`
    FOREIGN KEY (`ticket`)
    REFERENCES `BuyMe`.`support_record` (`support_ticket`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BuyMe`.`microsoft_xbox`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyMe`.`microsoft_xbox` (
  `xbox_id` INT NULL DEFAULT NULL,
  `ssd_size` VARCHAR(20) NULL DEFAULT NULL,
  `digital_or_disc` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `xbox_id_idx` (`xbox_id` ASC) VISIBLE,
  CONSTRAINT `xbox_id`
    FOREIGN KEY (`xbox_id`)
    REFERENCES `BuyMe`.`video_game_consoles` (`console_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BuyMe`.`nintendo_switch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyMe`.`nintendo_switch` (
  `id` INT NULL DEFAULT NULL,
  `screensize` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `multiple_playmodes` VARCHAR(4) NULL DEFAULT NULL,
  `oled_or_lcd` VARCHAR(4) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  INDEX `id_idx` (`id` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`id`)
    REFERENCES `BuyMe`.`video_game_consoles` (`console_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BuyMe`.`sony_playstation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyMe`.`sony_playstation` (
  `playstation_id` INT NULL DEFAULT NULL,
  `digital_or_disc` VARCHAR(20) NULL DEFAULT NULL,
  INDEX `id_idx` (`playstation_id` ASC) VISIBLE,
  CONSTRAINT `playstation_id`
    FOREIGN KEY (`playstation_id`)
    REFERENCES `BuyMe`.`video_game_consoles` (`console_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BuyMe`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyMe`.`staff` (
  `staffid` INT NOT NULL,
  `username` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `position` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`staffid`),
  INDEX `username_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `username`
    FOREIGN KEY (`username`)
    REFERENCES `BuyMe`.`accounts` (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
